# Generated by Django 6.0.5 on 2026-05-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='business',
            name='booking_count',
        ),
        migrations.RemoveField(
            model_name='business',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='business',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='plan',
        ),
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='business_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
